### PR TITLE
Feature/cc backend post advert

### PR DESCRIPTION
**Pull request by OpaJaa**
Post advert route for backend. Tested to work with MT-service. Also some unit tests for backend.

Lots of stuff here, hoping for a lot of comments so I can improve. My head is now completely empty.

Some minor logging-changes to MT-service. Can be removed, if not necessary.

### CODE REVIEW

**Review by bunjovis — COMMENTED** [review]
Working fine with valid data and token, but in error situations, all the errors are coming with "Request failed with status code xxx" and status code of 200, which means OK. This could be improved. Also, PR page says "This branch has conflicts that must be resolved
Use the web editor or the to resolve conflicts.
Conflicting files
cc-backend/src/utils.ts "

**Comment by OpaJaa** [comment]
> Working fine with valid data and token, but in error situations, all the errors are coming with "Request failed with status code xxx" and status code of 200, which means OK. This could be improved. Also, PR page says "This branch has conflicts that must be resolved
> Use the web editor or the to resolve conflicts.
> Conflicting files
> cc-backend/src/utils.ts "

Pulled main and merged -> fixed conflicts.
I have to check the status code issue. Didn't even notice it in my own testing, but I think I only read the json error response and not the "real" code.

**Comment by MSurvonen** [comment]
I didn't try but may cause some problems. Calling getToken in advertRoutes and if token is not a Bearer token. Then getToken returns a string 'Not a Bearer token' and in advertRoutes are no checks if the string is a token or just a message 'Not bearer token'.

**Comment by OpaJaa** [comment]
> I didn't try but may cause some problems. Calling getToken in advertRoutes and if token is not a Bearer token. Then getToken returns a string 'Not a Bearer token' and in advertRoutes are no checks if the string is a token or just a message 'Not bearer token'.

Added a check for this. Now returns code 498 if this check fails.

**Comment by OpaJaa** [comment]
> Working fine with valid data and token, but in error situations, all the errors are coming with "Request failed with status code xxx" and status code of 200, which means OK. This could be improved. Also, PR page says "This branch has conflicts that must be resolved
> Use the web editor or the to resolve conflicts.
> Conflicting files
> cc-backend/src/utils.ts "

Fixed status code transmitting. Now should work.

**Review by bunjovis — APPROVED** [review]

**Pull request merged**
